name: Scheduled Python Script - iCloud Cleaner
on:
  workflow_dispatch:
  schedule:
    # Runs at 5 PM UTC every Saturday
    - cron: '0 17 * * 6'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run the mail cleaning script
        env:
          ICLOUD_USERNAME: ${{ secrets.ICLOUD_USERNAME }}
          ICLOUD_PASSWORD: ${{ secrets.ICLOUD_PASSWORD }}
        run: python src/icloud-mail-clean-gh-action.py
